export const GET_PRODUCTS_DETAILS_SUCCESS = "GET_PRODUCTS_DETAILS_SUCCESS";
export const GET_PRODUCTS_DETAILS_FAILURE = "GET_PRODUCTS_DETAILS_FAILURE";
export const POST_USERS_DETAILS_SUCCESS = "POST_USERS_DETAILS_SUCCESS";
export const POST_USERS_DETAILS_FAILURE = "POST_USERS_DETAILS_FAILURE";
